version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: circleci/node@4.7.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: "s3://memo-client/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  s3-example:
    jobs:
      - build