name: Deploy quantum terminals

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: yarn install --frozen-lockfile --ignore-scripts

    - name: Running Test
      run: yarn test
